- name: Setup NGINX on localhost
  hosts: localhost
  become: true

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: start
      service:
        name: nginx
        state: started
        enabled: true
